### ISSUE TITLE
Como fazer a requisição do tipo GET em uma page dynamic table passando os parâmetros necessários de token e header?

### ISSUE THREAD

**Issue by whalyf** [po-ui/po-angular#2233]
Estou utilizando uma PAGE DYNAMIC TABLE para carregar os dados que vem da minha api, no entanto para realizar o get dos dados, preciso passar não somente a URL mas também o token para validação. Como e onde fazer isso?

**Comment by abananyabera** [comment]
@whalyf In Angular, you can make something called an "interceptor." Think of it like a helpful tool that automatically adds a specific header (like a label) to every message your app sends out. Instead of adding that label to each message individually, you create this tool once, and it takes care of it for you every time. This makes things easier and keeps your code cleaner!

**Comment by whalyf** [comment]
Thanks, i've implemented this way. Yeah it will be better to deal with api calls.

**Comment by whalyf** [comment]
Thanks, i've implemented this way. Yeah it will be better to deal with api calls.
